# Generated by Django 2.1.5 on 2019-01-09 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('authorities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('cities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('place', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('finishes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Iraq', max_length=80, unique=True)),
                ('abbreviation', models.CharField(default='IQ', max_length=2, unique=True)),
                ('population', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('states', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=40)),
                ('id_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Authority')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('teams', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('46fa8ab3-11f2-4aa6-bea2-dcd150819fd6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('number_of_teams', models.IntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('tournaments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='finish',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='finish',
            name='id_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
        ),
        migrations.AddField(
            model_name='city',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
