# Generated by Django 2.1.4 on 2018-12-28 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.UUID('734aa0c8-13ad-4d10-a31a-8f9389930ddf'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=80)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=80)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('place', models.IntegerField()),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=80)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=80)),
                ('team_text', models.CharField(default='default_team_text', max_length=200)),
                ('description', models.TextField()),
                ('kind', models.CharField(max_length=40)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Club')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=80)),
                ('number_of_teams', models.IntegerField()),
            ],
            bases=('api.basemodel',),
        ),
        migrations.AddField(
            model_name='finish',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='finish',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
