# Generated by Django 2.1.4 on 2019-01-01 00:54

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('19a8834e-eb2d-47d9-8d31-5f1bb12ff51e'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Iraq', max_length=80)),
                ('abbreviation', models.CharField(default='IQ', max_length=2)),
                ('population', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('states', django.db.models.manager.Manager()),
            ],
        ),
    ]
