# Generated by Django 2.1.4 on 2018-12-28 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9a879d99-b75d-41ba-9986-ed6f6646d801'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
