# Generated by Django 2.1.4 on 2018-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_text',
            field=models.CharField(default='hi', max_length=200),
        ),
    ]
