# */vasserballverband/docker/docker-compose.yml

version: "3.7" # corresponds to Docker Engine 18.06+ 
networks:
  primary-network:

services:
  reverse_proxy:
    container_name: nginx
    image: nginx:1.15-alpine 
    networks:
      - primary-network
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # as of now the database is handled by SQLite which is attached to app   
  #database:

  appserver:
    container_name: top_ie
    image: alpine:3.9
    networks:
      - primary-network

    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart_policy:
      condition:    on-failure
      delay:        5s
      max_attempts: 3
      window:       120s
    command: python3 manage.py runserver 0.0.0.0:8000  
 
