version: 3.7
services:
    api:
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        container_name: api
        ports:
            - "8000:8000"
        networks:
            - primary-network
        volumes:
            - .:/code
        de
