---

- name: Ansible playbook to be ran locally for single server
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      upgrade: yes
      cache_valid_time: 86400

  - name: Python 3.6.7 is pre-stalled on Ubuntu 18.04 so install pip3+tree
    become: true
    apt:
      name: python3-pip

  - name: Install tree to easily visualize file structure
    become: true
    apt:
      name: tree

  - name: Install Django dependencies, tools, and utilities
    become: true
    pip:
      executable: pip3
      name: 
        - django
        - djangorestframework
        - django_extensions
        - coreapi
    
  - name: Install wget as it is required to install terraform
    become: true
    apt:
      name: unzip
  
  - name: Pull Terraform archive
    get_url:
      url: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      dest: .

  - name: Unzip terraform package
    unarchive:
      src: ./terraform_*
      dest: /usr/local/bin

  - name: Delete terraform archive after having unzipped it
    file:
      path: ./terraform_*
      state: absent

  - name: Install Docker for Jenkins
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

  - name: Do that
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      


